### ISSUE TITLE
Grid Object .crs Attribute is None 

### ISSUE THREAD

**Issue by mrush-usgs** [usgs/sfrmaker#114]
Hello, Thank you for this package. I am trying to build an SFR package for an existing MODFLOW6 model. Using a couple different approaches, the .to_sfr() method fails with AssertionError: No destination CRS.

Traceback (most recent call last):
  File "C:\Users\mrush\OneDrive - DOI\Desktop\SFR\build.py", line 21, in <module>
    sfrdata = lines.to_sfr(grid=grid, model=md, model_length_units='feet')
  File "C:\Users\mrush\Anaconda3\envs\sfrmaker\lib\site-packages\sfrmaker\lines.py", line 730, in to_sfr
    self.to_crs(grid.crs)
  File "C:\Users\mrush\Anaconda3\envs\sfrmaker\lib\site-packages\sfrmaker\lines.py", line 319, in to_crs
    assert dest_crs is not None, "No destination CRS."
AssertionError: No destination CRS.

It appears the .crs attribute of the grid object is "None". My first approach was to pass a md.modelgrid object, e.g.:
sim = flopy.mf6.MFSimulation.load(model_name, 'mf6', 'mf6', model_path, verbosity_level=0)
md = sim.get_model()
sfrdata = lines.to_sfr(grid=md.modelgrid, model=md, model_length_units='feet')

I have also tried the shapefile approach without success:
grid = sfrmaker.StructuredGrid.from_shapefile(shapefile='LA_ModelGrid_Clipped.shp',
                                              icol='Row',  # attribute field with row information
                                              jcol='Column_',  # attribute field with column information
                                              active_area='LA_ModelGrid_Clipped.shp',
                                              crs='epsg:26911')  # NAD 1983 UTM Zone 11N

**Comment by aleaf** [comment]
Hi @mrush-usgs, the "No destination CRS" error makes it seem like the grid isn't referenced. The modelgrid instance generated by flopy on load of your model may be incorrect or incomplete. It's probably best to create a model grid instance from scratch [as shown in the example](https://usgs.github.io/sfrmaker/latest/notebooks/SFRmaker_demo.html#Specifying-a-model-grid-from-a-flopy-StructuredGrid-instance). Re: the shapefile approach, can you post the code you are using and any error traceback(s)?

**Comment by mrush-usgs** [comment]
Thank you for your help - I will try creating a new modelgrid instance. Here is my code + error for the shapefile approach: 

import flopy as fp
import sfrmaker
import os

lines = sfrmaker.Lines.from_nhdplus_v2(NHDFlowlines='NHDFlowline.shp',
                                    PlusFlowlineVAA='PlusFlowlineVAA.dbf',
                                    PlusFlow='PlusFlow.dbf',
                                    elevslope='elevslope.dbf',
                                    filter='LA_ModelGrid_Clipped.shp')
model_name = 'lab_model'
model_path = os.path.join('..', 'SUSTAIN', 'Working', model_name)
sim = fp.mf6.MFSimulation.load(model_name, 'mf6', 'mf6', model_path, verbosity_level=0)
md = sim.get_model()
grid = sfrmaker.StructuredGrid.from_shapefile(shapefile='LA_ModelGrid_Clipped.shp',
                                              icol='Row',  # attribute field with row information
                                              jcol='Column_',  # attribute field with column information
                                              active_area='LA_ModelGrid_Clipped.shp',
                                              crs='epsg:26911')  # NAD 1983 UTM Zone 11N
sfrdata = lines.to_sfr(grid=grid, model=md, model_length_units='feet')





Traceback (most recent call last):
  File "C:\Users\mrush\OneDrive - DOI\Desktop\SFR\build.py", line 21, in <module>
    sfrdata = lines.to_sfr(grid=grid, model=md, model_length_units='feet')
  File "C:\Users\mrush\Anaconda3\envs\sfrmaker\lib\site-packages\sfrmaker\lines.py", line 730, in to_sfr
    self.to_crs(grid.crs)
  File "C:\Users\mrush\Anaconda3\envs\sfrmaker\lib\site-packages\sfrmaker\lines.py", line 319, in to_crs
    assert dest_crs is not None, "No destination CRS."
AssertionError: No destination CRS.
