### ISSUE TITLE
Issues installing sfrmaker

### ISSUE THREAD

**Issue by porterma** [usgs/sfrmaker#130]
I am running into problems while installing sfrmaker. I have tried several methods from the github site and none of them appear to be working.

I downloaded the the sfrmaker .zip file. In the sfrmaker directory I ran `conda env create -f requirements.yml`, which resulted inthe following error:
> Running command git clone --filter=blob:none --quiet git://github.com/modflowpy/flopy 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-uiozv891'
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error
   × git clone --filter=blob:none --quiet git://github.com/modflowpy/flopy 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-uiozv891' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
   note: This error originates from a subprocess, and is likely not a problem with pip.
`error:` subprocess-exited-with-error
× git clone --filter=blob:none --quiet git://github.com/modflowpy/flopy 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-uiozv891' did not run successfully.
│ exit code: 128
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
failed
CondaEnvException: Pip failed

I commented out the the pip line for flopy in the requirements.yml, installed flopy (`pip install flopy`) in the sfrmaker env and then ran `conda env update -f requirements.yml` whicih gave me this error:

> Installing pip dependencies: | Ran pip subprocess with arguments:
['C:\\ProgramData\\Anaconda3\\envs\\sfrmaker\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'O:\\ModelingTools\\software\\usgs\\sfrmaker-develop\\condaenv.8rx6teaf.requirements.txt']
Pip subprocess output:
Collecting git+git://github.com/aleaf/modflow-export@develop (from -r O:\ModelingTools\software\usgs\sfrmaker-develop\condaenv.8rx6teaf.requirements.txt (line 2))
  Cloning git://github.com/aleaf/modflow-export (to revision develop) to c:\users\mporter\appdata\local\temp\pip-req-build-ia6_m17o
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet git://github.com/aleaf/modflow-export 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-ia6_m17o'
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
  error: subprocess-exited-with-error
  × git clone --filter=blob:none --quiet git://github.com/aleaf/modflow-export 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-ia6_m17o' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× git clone --filter=blob:none --quiet git://github.com/aleaf/modflow-export 'C:\Users\mporter\AppData\Local\Temp\pip-req-build-ia6_m17o' did not run successfully.
│ exit code: 128
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
failed
CondaEnvException: Pip failed

This is similar to the flopy error, but for sfrmaker. I then ran `pip install sfrmaker` and got this 

> Successfully installed gis-utils-0.3.2 modflow-export-0.1.0 sfrmaker-0.9.1

I ran ipython and tired to import sfrmaker and got this 

> ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import sfrmaker
File O:\ModelingTools\software\usgs\sfrmaker-develop\sfrmaker\__init__.py:6, in <module>
      4 from ._version import get_versions
      5 from sfrmaker.grid import StructuredGrid, UnstructuredGrid
----> 6 from sfrmaker.lines import Lines
      7 from sfrmaker.mf5to6 import Mf6SFR
      8 from sfrmaker.rivdata import RivData
File O:\ModelingTools\software\usgs\sfrmaker-develop\sfrmaker\lines.py:16, in <module>
     14 from sfrmaker.grid import StructuredGrid
     15 from sfrmaker.nhdplus_utils import load_nhdplus_v2, get_prj_file, load_nhdplus_hr
---> 16 from sfrmaker.sfrdata import SFRData
     17 from sfrmaker.units import convert_length_units, get_length_units
     18 from sfrmaker.utils import (width_from_arbolate_sum, arbolate_sum)
File O:\ModelingTools\software\usgs\sfrmaker-develop\sfrmaker\sfrdata.py:16, in <module>
     14 from sfrmaker.checks import valid_rnos, valid_nsegs, rno_nseg_routing_consistent
     15 from sfrmaker.elevations import smooth_elevations
---> 16 from sfrmaker.flows import add_to_perioddata, add_to_segment_data
     17 from sfrmaker.gis import export_reach_data, project
     18 from sfrmaker.observations import write_gage_package, write_mf6_sfr_obsfile, add_observations
File O:\ModelingTools\software\usgs\sfrmaker-develop\sfrmaker\flows.py:11, in <module>
      9 from sfrmaker.routing import find_path, make_graph
     10 from gisutils import shp2df
---> 11 from mfexport.budget_output import read_sfr_output
     12 from .fileio import read_tables
     13 from .routing import get_next_id_in_subset
File C:\ProgramData\Anaconda3\envs\sfrmaker\lib\site-packages\mfexport\__init__.py:9, in <module>
      7 from .grid import load_modelgrid, MFexportGrid
      8 from .mfexport import export, summarize
----> 9 from .results import export_heads, export_cell_budget, export_drawdown, export_sfr_results
     10 from .shapefile_export import export_shapefile
File C:\ProgramData\Anaconda3\envs\sfrmaker\lib\site-packages\mfexport\results.py:5, in <module>
      3 from flopy.utils.postprocessing import get_water_table
      4 from .array_export import export_array, export_array_contours
----> 5 from .budget_output import get_surface_bc_flux, read_sfr_output, get_flowja_face
      6 from gisutils import shp2df
      7 from .pdf_export import sfr_baseflow_pdf, sfr_qaquifer_pdf
File C:\ProgramData\Anaconda3\envs\sfrmaker\lib\site-packages\mfexport\budget_output.py:8, in <module>
      6 from flopy.utils.sfroutputfile import SfrFile
      7 import flopy.utils.binaryfile as bf
----> 8 from flopy.utils.mfgrdfile import MfGrdFile
      9 from .grid import get_kij_from_node3d
     12 def aggregate_sfr_flow_ja_face(df):
ModuleNotFoundError: No module named 'flopy.utils.mfgrdfile'

I looked at flopy on github and do not see a flopy.utils.mfgrdfile module.

Any thoughts on how to fix this. I've used sfrmaker in the past and it is great tool.

Thanks in advance!

**Comment by aleaf** [comment]
Hi @porterma, thanks for raising the issue. I think your first problem should be fixed by 706a282. And it looks like the second problem may be related to using an older version of sfrmaker, so hopefully resolving the install issue will fix that as well.

**Comment by porterma** [comment]
The switch from `git+git` to `git+https` in the .yml file did the trick. Thanks! I'll close the issue.
