### ISSUE TITLE
Adapting SFRmaker to work with NHDPlus Hi-Res

### ISSUE THREAD

**Issue by aleaf** [usgs/sfrmaker#97]
Adapt SFRmaker to read raw NHDPlus Hi-Res. Address issues with
* structure (read from geodatabase instead of shapefiles? should cover typical use-cases for getting hi-res from the National Map)
* if reading from shapefiles, should have an option to just supply foldernames and have SFRmaker find the flowlines and associated attribute tables within the file structure, just like for NHDPlus version 2
* Field names (NHDPlusID instead of COMID)
* Cast line_ids to strings to more easily deal with long NHDPlusIDs or a use case where lines are identified by names
* include option to use Divergence classification to deal with divergences
* any other issues that were encountered in the Neversink case?

Best approach would be to modify the functions in `nhdplus_utils.py` or add functions that parallel those for NHDPlus version 2.

@mnfienen @ntdosch

**Comment by mnfienen** [comment]
A few more considerations:
- To refactor COMID to use strings, will need to make sure `shp2df` and `pd.read_csv` to read in COMIDs as strings.
- Incorporate geopandas to use the geoDataFrame type for things returned from `shp2df`.
- Add method to `lines` specific to hires. Or, separate methods depending on similarity. 
- add download instructions to the documentation for the HiRes
